### ISSUE TITLE
Google has updated their SMTP settings again.

### ISSUE THREAD

**Issue by ktiedt** [gameldar/exim4#1]
`*.google.com:[email]:[password]`

is now:
`*.gmail.com:[email]:[password]`

Will submit a pull request, hoping you are willing to roll a new docker release from the fix, if not, I'll just rebuild locally but, figured I'd help others out who may be using your project too.

**Comment by gameldar** [comment]
Awesome - thank you - I had forgotten this was here... but I've also linked and kicked off the docker build too.
